---
- name: Install Java on Slave 1
  hosts: slave1
  become: yes

  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install OpenJDK Java 11
      apt:
        name: openjdk-11-jdk
        state: present
      when: ansible_os_family == "Debian"
